"""add score column

Revision ID: 09c1b51e0858
Revises: 553054345bc4
Create Date: 2026-01-18 05:56:06.427420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09c1b51e0858'
down_revision: Union[str, Sequence[str], None] = '553054345bc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_registrations', sa.Column('score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_registrations', 'score')
    # ### end Alembic commands ###
